# Generated by Django 4.0.5 on 2022-06-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='completed_distributions',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='completed_send_orders',
        ),
    ]
